version: "3"
services:
  apache:
    build: "./apache"
    image: "php:7.1-apache-laravel"
    links:
     - "mariadb:database"
     - "redis"
    ports:
     - "80:80"
    restart: "on-failure"
    volumes:
     - "./apache/sites-available:/etc/apache2/sites-available"
     - "./application:/var/www/html"
  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    restart: "on-failure"
    volumes:
     - "./database:/var/lib/mysql"
  redis:
    image: "redis"
    restart: "on-failure"
    volumes:
     - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
     - "./redis/data:/data"

