version: "3"
services:
  apache:
    build: "./apache"
    image: "php:7.1-apache-custom"
    links:
     - "mariadb:database"
    ports:
     - "80:80"
    restart: "on-failure"
    volumes:
     - "./apache/sites-available:/etc/apache2/sites-available"
     - "./application:/var/www/html"
  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    restart: "on-failure"
    volumes:
     - "./database:/var/lib/mysql"

